# Generated by Django 5.1.5 on 2025-02-03 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0002_remove_book_published_data_remove_member_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 5, 21, 33, 31, 847405)),
        ),
    ]
